'use client';
import { useMemo, useState } from 'react';
const questions=[
 {q:'How clearly are your highest-value AI opportunities defined?',a:['We have not identified them','We have a list of ideas','We have prioritized use cases','We have a funded portfolio tied to outcomes']},
 {q:'How consistently are workflows redesigned before AI is introduced?',a:['We add tools to existing processes','It happens occasionally','Priority workflows are deliberately redesigned','Workflow redesign is a standard operating discipline']},
 {q:'How ready is your data for practical AI use?',a:['Fragmented and difficult to access','Usable for a few teams','Governed and accessible for priority use cases','Trusted, connected, and designed for reuse']},
 {q:'How mature is your AI governance?',a:['No formal governance','Policies are being developed','Clear controls exist for priority use cases','Governance is embedded without slowing delivery']},
 {q:'How well equipped are employees to adopt AI?',a:['Limited awareness','Some training and experimentation','Role-based enablement is underway','AI is embedded into how teams work and improve']},
 {q:'How well do you measure AI business impact?',a:['We track activity only','We track time saved','We track operational and financial outcomes','We continuously optimize a portfolio against value']}
];
export default function Assessment(){const [answers,setAnswers]=useState({});const total=useMemo(()=>Object.values(answers).reduce((s,v)=>s+v,0),[answers]);const complete=Object.keys(answers).length===questions.length;const pct=Math.round((Object.keys(answers).length/questions.length)*100);let level='Exploring';if(total>=19)level='Scaling';else if(total>=13)level='Building';else if(total>=7)level='Emerging';
 return <div className="assessment-shell"><div className="progress"><span style={{width:`${pct}%`}}/></div>{questions.map((item,i)=><section className="question-card" key={item.q}><span className="eyebrow">Question {i+1} of {questions.length}</span><h2>{item.q}</h2><div className="answer-grid">{item.a.map((a,j)=><button key={a} className={answers[i]===j+1?'answer selected':'answer'} onClick={()=>setAnswers({...answers,[i]:j+1})}><span>{j+1}</span>{a}</button>)}</div></section>)}{complete&&<section className="result-card"><span className="eyebrow">Your current stage</span><h2>{level}</h2><p>Your score is <strong>{total} out of 24</strong>. The fastest path forward is to connect business priorities to a small number of redesigned workflows, then build the data, governance, and adoption model around them.</p><a className="button" href="/#contact">Discuss the results</a></section>}</div>}
