/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HowWeBuildRouteImport } from './routes/how-we-build'
import { Route as ForOrganizationsRouteImport } from './routes/for-organizations'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsProductSlugRouteImport } from './routes/products.$productSlug'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HowWeBuildRoute = HowWeBuildRouteImport.update({
  id: '/how-we-build',
  path: '/how-we-build',
  getParentRoute: () => rootRouteImport,
} as any)
const ForOrganizationsRoute = ForOrganizationsRouteImport.update({
  id: '/for-organizations',
  path: '/for-organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductSlugRoute = ProductsProductSlugRouteImport.update({
  id: '/products/$productSlug',
  path: '/products/$productSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/for-organizations': typeof ForOrganizationsRoute
  '/how-we-build': typeof HowWeBuildRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/products/$productSlug': typeof ProductsProductSlugRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/for-organizations': typeof ForOrganizationsRoute
  '/how-we-build': typeof HowWeBuildRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/products/$productSlug': typeof ProductsProductSlugRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/for-organizations': typeof ForOrganizationsRoute
  '/how-we-build': typeof HowWeBuildRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/products/$productSlug': typeof ProductsProductSlugRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/contact'
    | '/cookies'
    | '/for-organizations'
    | '/how-we-build'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/trust'
    | '/products/$productSlug'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/contact'
    | '/cookies'
    | '/for-organizations'
    | '/how-we-build'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/trust'
    | '/products/$productSlug'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/contact'
    | '/cookies'
    | '/for-organizations'
    | '/how-we-build'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/trust'
    | '/products/$productSlug'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  ForOrganizationsRoute: typeof ForOrganizationsRoute
  HowWeBuildRoute: typeof HowWeBuildRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TrustRoute: typeof TrustRoute
  ProductsProductSlugRoute: typeof ProductsProductSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-build': {
      id: '/how-we-build'
      path: '/how-we-build'
      fullPath: '/how-we-build'
      preLoaderRoute: typeof HowWeBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-organizations': {
      id: '/for-organizations'
      path: '/for-organizations'
      fullPath: '/for-organizations'
      preLoaderRoute: typeof ForOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productSlug': {
      id: '/products/$productSlug'
      path: '/products/$productSlug'
      fullPath: '/products/$productSlug'
      preLoaderRoute: typeof ProductsProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  ForOrganizationsRoute: ForOrganizationsRoute,
  HowWeBuildRoute: HowWeBuildRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TrustRoute: TrustRoute,
  ProductsProductSlugRoute: ProductsProductSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
